'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { Menu, X, Sprout, ArrowRight, User, LogOut } from 'lucide-react'
import { getCurrentUser, signOut, type UserProfile } from '@/lib/auth'
import { consumeAuthRedirectTarget } from '@/lib/authRedirectHelper'
const NAV_LINKS=[{label:'3단계 조립법',href:'#guide'},{label:'핵심 혜택',href:'#why'},{label:'활용 사례',href:'#usecases'},{label:'가격 안내',href:'#pricing'}]
export default function HeaderNav(){const router=useRouter();const[isOpen,setIsOpen]=useState(false);const[user,setUser]=useState<UserProfile|null>(null);useEffect(()=>{getCurrentUser().then(u=>{setUser(u);const target=consumeAuthRedirectTarget();if(u&&target&&target!=='/')router.replace(target)})},[router]);const logout=async()=>{await signOut();setUser(null)};return <header className="fixed top-0 left-0 right-0 z-50 border-b border-[#E8E5DD]/80 bg-[#FBFBF9]/90 backdrop-blur-md"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-4 sm:px-6"><Link href="/" className="flex items-center gap-2"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#3E5F48] text-white"><Sprout size={19} strokeWidth={1.75}/></span><span className="text-lg font-bold tracking-tight text-[#242825]">하루</span><span className="hidden text-xs text-[#6D736C] sm:inline">나만의 작은 웹 공방</span></Link><nav className="hidden items-center gap-7 md:flex">{NAV_LINKS.map(l=><a key={l.href} href={l.href} className="text-sm text-[#6D736C] transition-colors hover:text-[#3E5F48]">{l.label}</a>)}</nav><div className="hidden items-center gap-3 md:flex">{user?<><Link href="/dashboard" className="flex items-center gap-1.5 text-sm text-[#6D736C]"><User size={15}/>{user.name}</Link><button onClick={logout} className="text-[#6D736C]" aria-label="로그아웃"><LogOut size={15}/></button></>:<Link href="/login" className="text-sm text-[#6D736C]">로그인</Link>}<Link href="/builder" className="flex items-center gap-2 rounded-xl bg-[#3E5F48] px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-[#2D4835]">지금 조립 시작하기<ArrowRight size={15}/></Link></div><button className="rounded-lg p-2 text-[#3E5F48] md:hidden" onClick={()=>setIsOpen(!isOpen)} aria-label="메뉴 열기">{isOpen?<X size={21}/>:<Menu size={21}/>}</button></div>{isOpen&&<nav className="flex flex-col gap-1 border-t border-[#E8E5DD] bg-[#FBFBF9] px-5 py-4 md:hidden">{NAV_LINKS.map(l=><a key={l.href} href={l.href} onClick={()=>setIsOpen(false)} className="rounded-lg px-3 py-3 text-sm text-[#6D736C]">{l.label}</a>)}<Link href="/login" className="mt-2 rounded-xl bg-[#3E5F48] px-4 py-3 text-center text-sm font-semibold text-white">지금 조립 시작하기</Link></nav>}</header>}
